In [ ]:
arr = np.array([1,2,3,4,5], dtype='S')
print(arr)
print(arr.dtype)


[b'1' b'2' b'3' b'4' b'5']
|S1


# NumPy
- Numerical Python
- 배열(Array)을 다루는 파이썬 라이브러리
- 머신러닝 연산과정에서 필수적
- 오픈소스 프로젝트이며, 무료로 사용 가능

In [ ]:
%pip install numpy

In [ ]:
# 불러오기
import numpy as np

In [ ]:
# 버전 확인
print(np.__version__)

1.23.5


In [ ]:
# numpy array 만들기 - 1차원
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))
print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


In [ ]:
# 2차원 numpy array

arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3차원 numpy array
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
# array 차원 확인
print(arr.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [ ]:
# 더 높은 차원의 array
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print(arr.ndim, '차원')

[[[[[1 2 3 4]]]]]
5 차원


# Array Indexing

In [ ]:
# 1차원 array에 접근
arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[1])
print(arr[2]+arr[3])

1
2
7


In [ ]:
# 2차원 array에 접근
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('첫번째 차원의 두번째 개체 : ', arr[0, 1])

첫번째 차원의 두번째 개체 :  2


In [ ]:
# 3차원 array에 접근
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print('첫번째 array의 두번째 array의 세번째 개체 : ', arr[0, 1, 2])

첫번째 array의 두번째 array의 세번째 개체 :  6


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1])

[4 5 6]


In [ ]:
# negative indexing
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2번째 차원의 마지막 개체 : ', arr[1, -1])

2번째 차원의 마지막 개체 :  10


# Array Slicing

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(arr[1:5])
print(arr[1:5:2])
print(arr[:3])
print(arr[5:])

[2 3 4 5]
[2 4]
[1 2 3]
[ 6  7  8  9 10]


In [ ]:
# negative slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(arr[-4:-1])

[7 8 9]


In [ ]:
# 2차원 array slicing - 두번째 개체에서 index 1부터 2까지 반환
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:3])

[7 8]


In [ ]:
# 2차원 array slicing - 각 개체에서 index 2의 개체 반환
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [ ]:
# 2차원 array slicing - 각 개체에서 index 1부터 3까지의 개체 반환
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


# NumPy Data Types

In [ ]:
# 데이터타입 확인 - 정수
arr = np.array([1, 2, 3, 4, 5])

print(arr.dtype)

int64


In [ ]:
# 데이터타입 확인 - 유니코드 문자
arr = np.array(['ditto', 'OMG', 'Attention', 'Super Shy'])

print(arr.dtype)

<U9


In [ ]:
# array 생성시 데이터타입 지정하기 - 4비트 integer로 지정
arr = np.array([1, 2, 3, 4, 5], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [ ]:
# array 생성시 데이터타입 지정하기 - String으로 지정
arr = np.array([1, 2, 3, 4, 5], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [ ]:
# string to integer와 같이, 자료형 변환이 안되는 경우 ValueError가 난다.

# 아랫줄에서 #을 제거하고 실행해보세요.
arr = np.array(['1', '2'], dtype='i')

# arr = np.array(['1', 'a'], dtype='i')
print(arr)

ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
# 기존에 존재하는 array를 데이터타입 바꾸어 새 array로 만들기

arr = np.array([1.1, 2.2, 3.3])

newarr = arr.astype('i') # arr.astype('int') 로 사용해도 된다.

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
# integer로 구성된 array를 boolean 타입 array로 만들기
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


# Reshape

In [ ]:
# 1차원에서 2차원으로 변환
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 6)

print(newarr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
# 1차원에서 3차원으로 변환
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 2, 3)

print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# Unknown Dimension - 남은 수 하나를 -1로 주면 알아서 reshape해준다.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(1, 1, -1)
print(newarr)

[[[ 1  2  3  4  5  6  7  8  9 10 11 12]]]


In [ ]:
# Flattening - 1차원 배열로 변환해줌
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)
# newarr = arr.reshape(6) 과 같다.

print(newarr)

[1 2 3 4 5 6]


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]]])

newarr = arr.reshape(1, 6)

print(newarr)

[[1 2 3 4 5 6]]


---
### 문제 1
아래 1차원 배열을 다음과 같은 배열로 바꿔보세요.

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

# b = a.reshape(6, 1)
# b = a.reshape(6, -1)
b = a.reshape(-1, 1)

print(b)
# Output:
# [[1]
#  [2]
#  [3]
#  [4]
#  [5]
#  [6]]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


### 문제 2

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

b = a.reshape(3, 2)
# b = a.reshape(3, -1)
# b = a.reshape(-1, 2)

print(b)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]]

[[1 2]
 [3 4]
 [5 6]]


### 문제 3

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])

# b = a.reshape(6)
b = a.reshape(-1)

print(b)
# Output:
# [1 2 3 4 5 6]

[1 2 3 4 5 6]


### 문제 4

In [ ]:
a = np.array([[[1, 2], [3, 4], [5, 6]],
              [[7, 8], [9, 10], [11, 12]]])

b = a.reshape(6, 2)
# b = a.reshape(6, -1)
# b = a.reshape(-1, 2)

print(b)
# Output:
# [[ 1  2]
#  [ 3  4]
#  [ 5  6]
#  [ 7  8]
#  [ 9 10]
#  [11 12]]

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


### 문제 5

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

b = a.reshape(1, 3, 4)
# b = a.reshape(-1, 3, 4)
# b = a.reshape(1, -1, 4)
# b = a.reshape(1, 3, -1)

print(b)
# Output:
# [[[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]]

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


---

# Iterating

In [ ]:
# 1차원 배열에서의 반복
arr = np.array([1, 2, 3])

for x in arr:
    # print(x)
    print(f'{x} : {type(x)}')

1 : <class 'numpy.int64'>
2 : <class 'numpy.int64'>
3 : <class 'numpy.int64'>


In [ ]:
# 2차원 배열에서의 반복 - 1
arr = np.array([[1, 2], [3, 4]])

for x in arr:
    # print(x)
    print(f'{x} : {type(x)}')

[1 2] : <class 'numpy.ndarray'>
[3 4] : <class 'numpy.ndarray'>


In [ ]:
# 2차원 배열에서의 반복 - 2
arr = np.array([[1, 2], [3, 4]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4


In [ ]:
# range - 3차원 일 때
arr = np.array([[[1, 2], [3, 4], [5, 6]],
                [[7, 8], [9, 10], [11, 12]]])

print(arr.shape)
print(arr.shape[0])
print(arr.shape[1])

(2, 3, 2)
2
3


In [ ]:
# 3차원에서 1차원 배열에 접근하는 반복문
for i in range(arr.shape[0]): # range(2) : 0, 1
    for j in range(arr.shape[1]): # range(3) : 0, 1, 2
        print(arr[i, j])

[1 2]
[3 4]
[5 6]
[7 8]
[ 9 10]
[11 12]


In [ ]:
# 3차원일 때 원소에 접근하는 반복문
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        for k in range(arr.shape[2]):
            print(arr[i, j, k])

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)
print(arr.shape[0])
print(arr.shape[1])

(2, 3)
2
3


In [ ]:
# range
arr = np.array([[1, 2, 3], [4, 5, 6]])

for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        print(arr[i, j])

1
2
3
4
5
6


In [ ]:
# ndenumerate
arr = np.array([[1, 2, 3], [4, 5, 6]])

for index, element in np.ndenumerate(arr):
    print(index, element)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [ ]:
# ndenumerate - 3차원
arr = np.array([[[1, 2], [3, 4], [5, 6]],
                [[7, 8], [9, 10], [11, 12]]])

for index, element in np.ndenumerate(arr):
    print(index, element)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(0, 2, 0) 5
(0, 2, 1) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 1, 0) 9
(1, 1, 1) 10
(1, 2, 0) 11
(1, 2, 1) 12


---
### 문제 1
[[[]]] 의 shape?

In [ ]:
arr = np.array([[[]]])

print(arr.shape)

(1, 1, 0)


### 문제 2

a를 Output과 같이 만들기 위한 iteration 구문 작성

In [ ]:
a = np.array([[[1, 2, 3], [4, 5, 6]]])

for x in a:
  for y in x:
    print(y)


# Output:
# [1 2 3]
# [4 5 6]

[1 2 3]
[4 5 6]


---

# Join/Split

In [ ]:
# concatenate()을 사용해 여러개의 1차원 array를 연결해보자
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])

# arr = np.concatenate((arr1, arr2))
arr = np.concatenate((arr2, arr1))

print(arr)

[3 4 1 2]


In [ ]:
# 2차원의 array를 axis=1 기준으로 연결해보자
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

joint_arr_0 = np.concatenate((arr1, arr2), axis=0)
joint_arr_1 = np.concatenate((arr1, arr2), axis=1)

print(joint_arr_0)
print(joint_arr_1)

# print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# array_split()을 사용해 하나의 array를 3개로 만들어보자
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


# where() - Array Search
- 배열에서 특정 값을 검색하고 일치하는 인덱스를 반환할 수 있다.
- 배열을 검색하려면 where() 메서드를 사용

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 2, 0, 2])

x = np.where(arr == 2)

print(x)
print(type(x[0]))

(array([2, 6, 8]),)
<class 'numpy.ndarray'>


In [ ]:
type(x)

tuple

# sort() - Array Sort
- 요소(elements)들을 정렬된 순서대로 배치하는 것을 의미함
- 순서가 있는 시퀀스는 숫자, 알파벳, 오름차순 또는 내림차순과 같이 요소에 해당하는 순서가 있는 모든 시퀀스
- NumPy ndarray 객체에는 지정된 배열을 정렬하는 sort()라는 함수가 있다.

In [ ]:
arr = np.array(['Newjeans', 'BTS', 'Black Pink'])

print(np.sort(arr))

# 반대방향으로 정렬
reversed_arr = np.sort(arr)[::-1]
print(reversed_arr)

['BTS' 'Black Pink' 'Newjeans']
['Newjeans' 'Black Pink' 'BTS']


In [ ]:
# 원본 array 는 바뀌지 않음
print(arr)

['Newjeans' 'BTS' 'Black Pink']


In [ ]:
# 숫자형 정렬
arr = np.array([5, 6, 7, 2, 9, 3, 0, 5, 6])

print(np.sort(arr))

# 반대방향으로 정렬
reversed_arr = np.sort(arr)[::-1]
print(reversed_arr)

[0 2 3 5 5 6 6 7 9]
[9 7 6 6 5 5 3 2 0]


In [ ]:
# 참고 - 문자열을 슬라이싱으로 뒤집을 수도 있다.
str_1 = 'Hello, World!'
print(str_1[::-1])

!dlroW ,olleH


# Filter
- 기존 배열에서 일부 요소를 가져와서 새 배열을 만드는 것을 필터링이라고 한다.
- NumPy에서는 boolean 인덱스 목록을 사용하여 배열을 필터링한다.

In [ ]:
arr = np.array([130, 162, 113, 107, 145])

x = [True, True, False, False, True]

newarr = arr[x]

print(newarr)

[130 162 145]


In [ ]:
newarr_false = [arr[i] for i in range(arr.shape[0]) if x[i] == False]
print(newarr_false)

[113, 107]


In [ ]:
newarr_false = []

for i in range(arr.shape[0]):
    if x[i] == False:
        newarr_false.append(arr[i])

print(newarr_false)

[113, 107]


In [ ]:
# for문과 if문을 이용해 filter array 만들기
arr = np.array([130, 162, 113, 107, 145])

filter_arr = []

for element in arr:
  if element > 120:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[True, True, False, False, True]
[130 162 145]
